// Generated by Wrangler on Sun May 19 2024 18:56:59 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  APP_DB: D1Database;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET;
}
